name: Build and Start Next.js Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: pnpm ci

      - name: Build Next.js app
        run: pnpm build

      - name: Start Next.js server
        run: |
          pnpm start &
          sleep 10
          curl http://localhost:3000 || exit 1

      - name: Run tests
        run: npm test
